cors:
  allowed:
    origins: http://localhost:3000

# This project uses Auth0 (https://auth0.com/) for authentication. These properties are needed to validate JWT tokens.
# The can be specified them in a application-default.yml file:
# - auth0.audience
# - spring.security.oauth2.resourceserver.jwt.issuer-uri
