version: '3.1'

services:

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-hello}
      POSTGRES_USER: ${DB_USER:-hello_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-hello_pw}
    ports:
      - "5432:5432"
    volumes:
      - hello_db_data:/var/lib/postgresql/data

volumes:
  hello_db_data:
