name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.16
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.2
      - name: Test and Build Node.js Application
        working-directory: react-ui
        env:
          CI: true
        run: |
          npm ci
          npm test
          npm run build
      - name: Deploy Node.js Application to Google Cloud Storage
        uses: actions-hub/gcloud@286.0.0
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          CLI: gsutil
        with:
          args: rsync -R react-ui/build gs://${{ secrets.GCP_BUCKET }}
