name: Node.js CI

on:
  push:
    branches: [master]
    paths: ['react-ui/**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.16
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.2
      - name: Test and Build Node.js Application
        working-directory: react-ui
        env:
          CI: true
          REACT_APP_HELLO_API: https://${{ secrets.API_HOSTNAME }}
          REACT_APP_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          REACT_APP_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
        run: |
          npm ci
          npm test
          npm run build
      - name: Deploy Node.js Application to Firebase
        working-directory: react-ui
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npx firebase-tools deploy --project ${{ secrets.GCP_PROJECT }}
